version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: myProject
      MYSQL_USER: el
      MYSQL_PASSWORD: el
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DB_HOST=mysql
      - DB_NAME=myProject
      - DB_USER=el
      - DB_PASSWORD=el
      - SECRET_KEY=your-secret-key-here
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./server:/app

  frontend:
    build: ./client
    ports:
      - "3000:80"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  mysql_data:
