# Generated by Django 5.2.6 on 2025-09-08 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movie_id', models.CharField(max_length=64)),
                ('movie_title', models.CharField(max_length=255)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('show_at', models.DateTimeField(blank=True, null=True)),
                ('seats', models.JSONField(default=list)),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('convenience_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=16)),
                ('Cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('booking_code', models.CharField(editable=False, max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
