# Generated by Django 5.2.6 on 2025-09-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Cancelled_at',
            new_name='cancelled_at',
        ),
    ]
